# Nome da pipeline
name: Run Basic Testes

# Em que momento será executada a pipeline
on: 
  pull_request:
    branches:
      - main
jobs:
  # o que será feito nessa pipeline
  # só teremos um job: rodar os testes
  cypress-run:
  # maquina que será executada a pipeline
    runs-on: ubuntu-latest

    # passo a passo para rodar os testes
    steps:
      # clone do projeto
      - name: Checkout Repository
        uses: actions/checkout@v3   

      #  exemplo de exeucução do terminal
      # instalar dependências
      - name: Install Dependencies
        run: npm install

      # execução e configuração do projeto
      - name: Run Tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # upload do relatório do mocha
      - name: Upload relatório
        uses: actions/upload-artifact@v3
        with:
          name: Relatório mocha
          path: cypress\reports\html
          
